---
name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: /create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2  # v1.11.5
        id: app_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/setup-java@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b  # v5.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: build
        run: |
          mvn clean install -DskipTests
          mvn test

      - name: Release Please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445  # v4.2.0
        with:
          release-type: java
          token: '${{ steps.app_token.outputs.token }}'
